export const FETCH_DATA_OF_CART_SUCCESS = "FETCH_DATA_OF_CART_SUCCESS";
export const FETCH_DATA_OF_CART_FAIL = "FETCH_DATA_OF_CART_FAIL";
export const ADD_DATA_TO_CART_SUCCESS = "ADD_DATA_TO_CART_SUCCESS";
export const ADD_DATA_TO_CART_FAIL = "ADD_DATA_TO_CART_FAIL";
export const DELETE_ITEM_FROM_CART_SUCCESS = "DELETE_ITEM_FROM_CART_SUCCESS";
export const DELETE_ITEM_FROM_CART_FAIL = "DELETE_ITEM_FROM_CART_FAIL";
